export const ROAD_NAME_ATTRIBUTE = 'ROAD_NAME';
export const ROAD_COMMON_USAGE_ATTRIBUTE = 'COMMON_USAGE_NAME';
export const ROAD_NETWORK_TYPE_ATTRIBUTE = 'NETWORK_TYPE';
export const BOUNDARY_NAME_ATTRIBUTE = 'name';

export const ROAD_TILE_ATTRIBUTES = [
    ROAD_NAME_ATTRIBUTE,
    ROAD_COMMON_USAGE_ATTRIBUTE,
    ROAD_NETWORK_TYPE_ATTRIBUTE,
] as const;
